version: '3'

services:
  spark_app:
    build:
      context: ./spark_app
    ports:
      - "8888:8888"
    command: "python logica_spark.py"

  flask_app:
    build:
      context: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - spark_app
    command: "python app.py"
